import "~/styles/globals.css";
import "@uploadthing/react/styles.css";

import { Space_Grotesk } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import TopNav from "~/components/layout/TopNav";
import { extractRouterConfig } from "uploadthing/server";
import { ourFileRouter } from "./api/uploadthing/core";
import { NextSSRPlugin } from "@uploadthing/react/next-ssr-plugin";

const font = Space_Grotesk({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <NextSSRPlugin
          /**
           * The `extractRouterConfig` will extract **only** the route configs
           * from the router to prevent additional information from being
           * leaked to the client. The data passed to the client is the same
           * as if you were to fetch `/api/uploadthing` directly.
           */
          routerConfig={extractRouterConfig(ourFileRouter)}
        />
      <html lang="en">
        <body className={`font-sans ${font.variable} flex-col gap-4`}>
          <TopNav />
          <main className="flex items-center justify-center">{children}</main>
        </body>
      </html>
    </ClerkProvider>
  );
}
