import "~/styles/globals.css";

import { Space_Grotesk } from "next/font/google";
import { StyledHeader } from "~/components/global/Styled";

const font = Space_Grotesk({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

function TopNav() {
  return (
    <nav className="flex w-full items-center justify-between border-b p-4 text-xl">
      <StyledHeader tag="h2" children="Gallery" />
    </nav>
  );
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`font-sans ${font.variable} flex-col gap-4`}>
        <TopNav />
        <main className="flex items-center justify-center">{children}</main>
      </body>
    </html>
  );
}
